//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Algorithm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Algorithm.IAlgorithmService")]
    public interface IAlgorithmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlgorithmService/BinarySearch", ReplyAction="http://tempuri.org/IAlgorithmService/BinarySearchResponse")]
        int BinarySearch(int[] mas, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlgorithmService/BinarySearch", ReplyAction="http://tempuri.org/IAlgorithmService/BinarySearchResponse")]
        System.Threading.Tasks.Task<int> BinarySearchAsync(int[] mas, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlgorithmService/Sort", ReplyAction="http://tempuri.org/IAlgorithmService/SortResponse")]
        int[] Sort(int[] mas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlgorithmService/Sort", ReplyAction="http://tempuri.org/IAlgorithmService/SortResponse")]
        System.Threading.Tasks.Task<int[]> SortAsync(int[] mas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlgorithmServiceChannel : Client.Algorithm.IAlgorithmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlgorithmServiceClient : System.ServiceModel.ClientBase<Client.Algorithm.IAlgorithmService>, Client.Algorithm.IAlgorithmService {
        
        public AlgorithmServiceClient() {
        }
        
        public AlgorithmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlgorithmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlgorithmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int BinarySearch(int[] mas, int id) {
            return base.Channel.BinarySearch(mas, id);
        }
        
        public System.Threading.Tasks.Task<int> BinarySearchAsync(int[] mas, int id) {
            return base.Channel.BinarySearchAsync(mas, id);
        }
        
        public int[] Sort(int[] mas) {
            return base.Channel.Sort(mas);
        }
        
        public System.Threading.Tasks.Task<int[]> SortAsync(int[] mas) {
            return base.Channel.SortAsync(mas);
        }
    }
}
